# stage #1
FROM golang:1.21 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o spacelift-promex .


# stage #2
FROM alpine:3.19
EXPOSE 9953

RUN apk add --no-cache ca-certificates
RUN apk upgrade --update-cache --available
RUN adduser --disabled-password --no-create-home --uid=1983 spacelift

COPY --from=builder /app/spacelift-promex /usr/bin/spacelift-promex
RUN chmod +x /usr/bin/spacelift-promex

CMD ["/usr/bin/spacelift-promex", "serve"]
